security:

    providers:
        our_db_provider:
            entity:
                class: App\Entity\User
                property: username


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            provider: our_db_provider
            form_login:
                login_path : login
                check_path : login
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: logout
                target : login

    encoders:
        App\Entity\User:
            algorithm : auto


    role_hierarchy:
        ROLE_CUSTOMER:
        ROLE_CONTROLLER:
        ROLE_ADMIN:          ROLE_CONTROLLER
        ROLE_SUPER_USER:     [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]


