INSERT INTO equipment_category (category,alias,accessories,has_periodic_control,has_commissioning_control,has_return_to_service_control) VALUES ('GRUE AUXILIAIRE DE CHARGEMENT','grue_auxiliaire',TRUE,TRUE,TRUE,TRUE );
INSERT INTO equipment_category (category,alias,accessories,has_periodic_control,has_commissioning_control,has_return_to_service_control) VALUES ('BRAS DE LEVAGE POUR BENNES AMOVIBLES','bras_de_levage',FALSE,TRUE,TRUE,TRUE);
INSERT INTO equipment_category (category,alias,accessories,has_periodic_control,has_commissioning_control,has_return_to_service_control) VALUES ('ELEVATEUR DE VEHICULES','elevateur_de_vehicules',FALSE,TRUE,FALSE,FALSE);
INSERT INTO equipment_category (category,alias,accessories,has_periodic_control,has_commissioning_control,has_return_to_service_control) VALUES ('CRIC MOBILE / TABLE ELEVATRICE / GRUE D ATELIER','cricMobile_tableElevatrice_grueDAtelier',FALSE,TRUE,FALSE,FALSE);
INSERT INTO equipment_category (category,alias,accessories,has_periodic_control,has_commissioning_control,has_return_to_service_control) VALUES ('HAYON ELEVATEUR','hayon_elevateur',FALSE,TRUE,TRUE,TRUE);
INSERT INTO equipment_category (category,alias,accessories,has_periodic_control,has_commissioning_control,has_return_to_service_control) VALUES ('CHARIOT ELEVATEUR / CHARGEUR FRONTAL','chariot_elevateur_chargeur_frontal',TRUE,TRUE,FALSE,FALSE);
INSERT INTO equipment_category (category,alias,accessories,has_periodic_control,has_commissioning_control,has_return_to_service_control) VALUES ('PLATE-FORME ELEVATRICE MOBILE DE PERSONNEL','plateforme_elevatrice',FALSE,TRUE,FALSE,FALSE);
INSERT INTO equipment_category (category,alias,accessories,has_periodic_control,has_commissioning_control,has_return_to_service_control) VALUES ('B.O.M. ET COMPACTEUR','bom_compacteur',FALSE,TRUE,FALSE,FALSE);
INSERT INTO equipment_category (category,alias,accessories,has_periodic_control,has_commissioning_control,has_return_to_service_control) VALUES ('PELLE HYDRAULIQUE','pelle_hydraulique',TRUE,TRUE,FALSE,FALSE);
INSERT INTO equipment_category (category,alias,accessories,has_periodic_control,has_commissioning_control,has_return_to_service_control) VALUES ('VEHICULE SUR PISTE','vehicule_sur_piste',FALSE,TRUE,FALSE,FALSE);
INSERT INTO equipment_category (category,alias,accessories,has_periodic_control,has_commissioning_control,has_return_to_service_control) VALUES ('PORTE ET PORTAIL AUTOMATIQUE ET SEMI-AUTOMATIQUE','porte_portail_automatique',FALSE,TRUE,FALSE,FALSE);
INSERT INTO equipment_category (category,alias,accessories,has_periodic_control,has_commissioning_control,has_return_to_service_control) VALUES ('PALAN / TREUIL','palan_treuil',TRUE,TRUE,FALSE,FALSE);
INSERT INTO equipment_category (category,alias,accessories,has_periodic_control,has_commissioning_control,has_return_to_service_control) VALUES ('CHARGEUSE PELLETEUSE','chargeuse_pelleteuse',TRUE,TRUE,FALSE,FALSE);

